feat: automatically generate the credentialName in the Login Component
goharbor/harbor-cli pull request #147
Opened 2024-08-02 15:27 UTC by karanngi

Hello Team,
This PR address the issue to automatically generate the credentialName in the Login Component.

Closes this  #37

2024-08-14 03:06 UTC, bupd requested changes

2024-08-14 03:06 UTC, bupd commented on cmd/harbor/root/login.go
> +
this is redundant, please remove.
```suggestion
```

2024-08-14 03:06 UTC, bupd commented on pkg/views/login/create.go
>  					if str == "" {
Update `Name of Credential` `validate block` with this code 

```suggestion
				Validate(func(str string) error {
					if str == "" {
						loginView.Name = fmt.Sprintf("%s@%s", loginView.Username, utils.SanitizeServerAddress(loginView.Server))
						return nil
					}
					return nil
				}),

```

This ensures that when `Credential name` is empty it is autofilled with the default value.

2024-11-10 21:12 UTC, Vad1mo commented
related https://github.com/goharbor/harbor-cli/pull/148

2024-11-11 13:41 UTC, bupd requested changes
please add the necessary changes and fix merge conflict.

2024-11-11 14:09 UTC, bupd commented
https://github.com/goharbor/harbor-cli/pull/147#discussion_r1716251981

Committing these suggestions will make this PR ready for merge

2024-11-12 15:55 UTC, closed without merging

2024-11-12 15:55 UTC, bupd commented
closing in favor of (#250)