created build-dev dagger function for enhance developer workflow
goharbor/harbor-cli pull request #169
Opened 2024-08-16 09:52 UTC by Althaf66

This fixes #163 

- Added build-dev dagger function to build the Harbor binary for development purposes.

- Updated existing Dagger functions with descriptions.

![Screenshot from 2024-08-16 11-42-41](https://github.com/user-attachments/assets/66804e3a-0ba1-4d2d-988e-b7cdbfcce11e)

2024-08-16 13:27 UTC, bupd requested changes

2024-08-16 13:27 UTC, bupd commented on main.go
> +// Function that responsible for handling tasks related to releasing the Harbor CLI tool.
```suggestion
// Release handles building, tagging, and publishing the Harbor CLI tool.
```

update description to be concise clear.

2024-08-16 13:27 UTC, bupd commented on main.go
> +}
- Update build-dev to produce binary out of the box without any args or flags such as directory.
- `dagger call build-dev` should work.

![Screenshot_2024-08-16_18-37-51](https://github.com/user-attachments/assets/00832e79-f772-4393-8970-405734c2d103)

2024-08-16 13:27 UTC, bupd commented on main.go
> +// Returns container environment for running Goreleaser with specific configurations.
same here!

2024-08-16 14:53 UTC, bupd commented
@Althaf66 Additionally, build-dev should actually be able to build harbor based on their system. So devs on windows and Linux can use it.

2024-08-18 08:17 UTC, bupd requested changes
Run your code with `go fmt ./...`

2024-08-18 08:17 UTC, bupd commented on main.go
> +// Return a container that build the Harbor binary for development purposes.
```suggestion
// builds Harbor-Cli binary for development purposes
```

2024-08-18 09:11 UTC, bupd requested changes
update the README with the command to build the binary using harbor.

cmd: `dagger call build-dev --source=. --goos=$(go env GOOS) --goarch=$(go env GOARCH) export --path=bin`

Dagger call does not support Host access & Host environment.
- https://docs.dagger.io/manuals/user/host-fs
- https://docs.dagger.io/manuals/user/host-env

2024-08-18 09:11 UTC, bupd commented on main.go
> +}
```suggestion
func (m *HarborCli) BuildDev( ctx context.Context, source *dagger.Directory, goos string, goarch string) *dagger.Directory {
	fmt.Println("🛠️  Building Harbor-Cli with Dagger...")

	// Define the path for the binary output
	binaryOutputPath := "/src/bin/harbor"
	return dag.Container().
		From("golang:latest").
		WithMountedDirectory("/src", source).
		WithWorkdir("/src/cmd/harbor").
		WithEnvVariable("GOOS", goos).
		WithEnvVariable("GOARCH", goarch).
		WithExec([]string{"go", "build", "-o", binaryOutputPath, "main.go"}).
		WithWorkdir("/src").Directory("/src/bin")
}

```

2024-08-18 09:11 UTC, bupd commented on main.go
> +}
This adds the required flow we need.

2024-10-25 15:14 UTC, Vad1mo commented
closing if favor https://github.com/goharbor/harbor-cli/pull/219

2024-10-25 15:14 UTC, closed without merging