feat: add cli for health status
goharbor/harbor-cli pull request #170
Opened 2024-08-16 12:56 UTC by mahbub570

This pr provides a status check of various system components, allowing administrators to quickly assess the overall health and operational status of the Harbor registry system.

Command:
`harbor health` : Get the health status of Harbor components

![health](https://github.com/user-attachments/assets/2ac3450a-7019-4658-8f88-ee144e7c36bd)

2024-08-16 14:55 UTC, bupd commented
@mahbub570 Have a look at #81. which does the same with colors.

2024-08-16 16:01 UTC, mahbub570 commented
I see, @bupd like this?

 
![health](https://github.com/user-attachments/assets/ca30164c-c462-4bae-a6cc-2d0a85cd2be4)

2024-08-16 18:51 UTC, bupd commented
Adjust the boudaries of the box

2024-08-18 08:07 UTC, bupd requested changes

2024-08-18 08:07 UTC, bupd commented on pkg/api/health_handler.go
> +	ctx := context.Background()
```suggestion
	ctx, client, err := utils.ContextWithClient()
	if err != nil {
		return err
	}
```

2024-08-18 08:07 UTC, bupd commented on pkg/views/health/view.go
Modify this to follow `user/list/view.go`.

2024-09-11 13:48 UTC, Althaf66 commented
@mahbub570  Make these changes in `pkg/views/health/view.go`

```go
package health

import (
	"fmt"
	"os"

	"github.com/charmbracelet/bubbles/table"
	"github.com/charmbracelet/bubbletea"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/health"
	"github.com/goharbor/harbor-cli/pkg/views"
	"github.com/goharbor/harbor-cli/pkg/views/base/tablelist"
)

var columns = []table.Column{
	{Title: "Component", Width: 18},
	{Title: "Status", Width: 26},
}

func PrintHealthStatus(status *health.GetHealthOK) {
	var rows []table.Row
	fmt.Printf("Harbor Health Status:: %s\n", styleStatus(status.Payload.Status))
	for _, component := range status.Payload.Components {
		rows = append(rows, table.Row{
			component.Name,
			styleStatus(component.Status),
		})
	}

	m := tablelist.NewModel(columns, rows, len(rows))

	if _, err := tea.NewProgram(m).Run(); err != nil {
		fmt.Println("Error running program:", err)
		os.Exit(1)
	}
}

func styleStatus(status string) string {
	if status == "healthy" {
		return views.GreenStyle.Render(status)
	}
	return views.RedStyle.Render(status)
}
```

2024-09-11 13:49 UTC, Althaf66 commented
`pkg/api/health_handler.go`

```go
package api

import (
	"fmt"

	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/health"
	"github.com/goharbor/harbor-cli/pkg/utils"
)

func GetHealth() (*health.GetHealthOK, error) {
	ctx, client, err := utils.ContextWithClient()
	if err != nil {
		return nil, err
	}

	response, err := client.Health.GetHealth(ctx,&health.GetHealthParams{})
	if err != nil {
		return nil, fmt.Errorf("error getting health status: %w", err)
	}

	return response, nil
}

```

2024-09-11 16:32 UTC, mahbub570 commented
thanks @Althaf66 for your suggestions.

2024-09-11 18:12 UTC, Althaf66 commented
ready for review

2024-09-21 10:31 UTC, bupd approved these changes
LGTM 🚀

2024-10-01 14:02 UTC, merged