Fix Validation Domain for login command
goharbor/harbor-cli pull request #271
Opened 2024-11-28 01:38 UTC by Standing-Man

fixed #269.

Add the Validation function

2024-12-03 14:49 UTC, Vad1mo commented
What happens for those use cases:

- subdomain.domain.com:port
- 127.0.0.1 and 127.0.0.1:8080
-

2024-12-03 14:50 UTC, Vad1mo requested changes
What happens for those use cases:

- subdomain with prot -> subdomain.domain.com:**port**
- ip -> 127.0.0.1 and 127.0.0.1:8080
- top level domain -> registry.com

2024-12-04 02:06 UTC, Standing-Man commented
Hi @Vad1mo, I gave another validation method to support subdomains with or without ports, IP addresses, and top-level domains. Additionally, validated that the top-level domain of the domain name has a minimum length of at least two characters.

2024-12-28 01:39 UTC, bupd requested changes
```bash
❯ ./harbor-dev login
┃ Server
┃ Server address eg. demo.goharbor.io
┃ > https://127.0.0.4:50

  User Name
  > lsadkjf

  Password
  >

  Name of Credential
  Name of credential to be stored in the harbor config file.
  > lsadkjf@1234-50

 * invalid domain format: too many colons
```

the above is a valid domain

## TIP
@Standing-Man, Instead of checking if the domain is valid. check only if its invalid by adding only these rules
Incorrect Domain Names:
```
http:// (missing domain)
https:// (missing domain)
http://example (missing TLD, not valid)
http://127.0.0.256 (invalid IP, exceeds valid octet range)
http://my_site.local (invalid local domain, underscores are not allowed in domain names)
https://example..com (double period, invalid syntax)
https://.example.com (leading dot in the domain, invalid)
http://-example.com/ (hyphen at the start, invalid)
https://example.c (single character TLD, invalid)
http://192.168.0.999 (invalid IP, octet exceeds range)
```
- Domain Names with Special Characters (Not Valid)
- http://example (missing TLD, not valid)

2025-01-01 09:22 UTC, Standing-Man commented
Hi @bupd, i'm confused about issue #297 and how to reproduce this issue. 
```
harbor login registry.bupd.xyz -> login successfully and store in config
harbor login http://registry.bupd.xyz/ -> failed to log in
```
or just
```
harbor login http://registry.bupd.xyz/  -> failed to pass the validation of server address
```
Anyway, i added more restrictions to validate server address and you can try to check if issue #297 solved.

2025-01-09 13:34 UTC, bupd commented
@Standing-Man server address with leading slash result in failed login. We should fix it.

2025-01-09 13:42 UTC, bupd requested changes

2025-01-09 13:42 UTC, bupd commented on pkg/utils/helper.go
> +	url := FormatUrl(domain)
In FormatUrl function. I would suggest adding the removal of leading slash.

2025-01-11 05:08 UTC, Standing-Man commented on pkg/utils/helper.go
> +	url := FormatUrl(domain)
<img width="789" alt="image" src="https://github.com/user-attachments/assets/fc9a8aee-8d2b-4eea-809b-2557beb71263" />

The URL `http://registry.bupd.xyz/` is still working for me, so I'm a bit unsure about what might be going wrong.

2025-02-11 01:20 UTC, bupd requested changes
Thanks for your contributions

Please do Rebase.

2025-02-26 02:42 UTC, closed without merging