270 add ldflags to dagger
goharbor/harbor-cli pull request #273
Opened 2024-11-28 21:24 UTC by qcserestipy

Fixes #270 

I added the ldflags to the buildDev and build function to account for the version flags.
Git needs to be installed on the fly in the dagger service to retrieve these values.

2024-11-28 22:09 UTC, bupd requested changes

2024-11-28 22:09 UTC, bupd commented on dagger/main.go
> +				go build -ldflags "-X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.Version=$(git describe --tags --always --dirty 2>/dev/null || echo \"v0.0.1\") \
We can have a static version for BuildDev. Which we can use `dev` as version.

2024-11-28 22:09 UTC, bupd commented on dagger/main.go
> +						go build -ldflags "-X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.Version=$(git describe --tags --always --dirty 2>/dev/null || echo \"v0.0.1\") \
There should be no fallback on version for production builds.

2024-11-28 22:09 UTC, bupd commented on dagger/harbor-dev
Remove bin files.

2024-11-28 22:09 UTC, bupd commented on dagger/main.go
> +								  -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.System=$(go env GOOS)/$(go env GOARCH)" \
Os and arch will be auto-generated by version command.

2024-12-17 14:19 UTC, bupd requested changes
Remove the binary file `harbor-dev`.

2024-12-17 14:20 UTC, bupd approved these changes
LGTM!

2024-12-28 00:41 UTC, bupd commented
@Vad1mo, if you're okay with the changes, we can proceed with merging this.

2025-01-06 13:15 UTC, Vad1mo approved these changes

2025-01-06 13:15 UTC, merged