Improved Error Messages
goharbor/harbor-cli pull request #282
Opened 2024-12-15 14:10 UTC by Roaster05

## Description
This draft PR enhances error messages for end users by replacing memory references with custom messages based on error codes and locations. These changes improve the clarity and usability of the error messages.

### Key Updates
- Implemented custom error messages for the `project_handler` module.
- Errors now provide detailed and actionable information.
  **Examples**:
  - `ERRO[0000] failed to create project: Project abc already exists`
  - `ERRO[0001] failed to delete project: Project my_project not found or already deleted`
- Error codes and types are mapped from the endpoint documentation:  
  [Harbor Go Client Documentation](https://pkg.go.dev/github.com/goharbor/go-client@v0.210.0/pkg/sdk/v2.0/client/project).

## Notes
- Current changes are restricted to the `project_handler` module.
- Additional modules will be updated after approval of this approach.

2024-12-20 07:11 UTC, Roaster05 commented
@bupd @Vad1mo could you please review this PR, Thanks

2024-12-28 02:32 UTC, bupd requested changes
Please follow the https://github.com/goharbor/harbor-cli/issues/262#issuecomment-2541545880

- remove the prefix as mentioned.

2024-12-29 14:33 UTC, Roaster05 commented
> Please follow the [#262 (comment)](https://github.com/goharbor/harbor-cli/issues/262#issuecomment-2541545880)
> 
>     * remove the prefix as mentioned.

@bupd the prefix is generated by the `Errorf` method of the `fmt` module, it we want to remove it we can use the `Print` method only, should i make that change?

2025-02-05 01:47 UTC, bupd requested changes
Thanks for your contributions.

I would suggest slog instead of logrus as mentioned in the below comment.

https://github.com/goharbor/harbor-cli/issues/262#issuecomment-2564864716

Thanks

2025-03-11 12:14 UTC, closed without merging