changes in artifact tags list cmd
goharbor/harbor-cli pull request #286
Opened 2024-12-17 11:52 UTC by Althaf66

This PR fixes #256 

Due to DCO failure, I created PR for the #257 

**Before**
![Screenshot from 2024-11-15 00-34-53](https://github.com/user-attachments/assets/2d2274c1-b2b4-4a63-944d-71de8cfb38b7)

**After**
`harbor artifact tags list`
![Screenshot from 2024-11-15 00-54-00](https://github.com/user-attachments/assets/cf573951-c7f6-4bad-ab0d-ae7870cd2d54)

And changed to 'project/repo@digest' format

2024-12-28 00:36 UTC, bupd requested changes
it shows empty for every artifacts??

We get data in json format. Please update the table to fix this.

```bash
❯ ./harbor-dev artifact list
┌───────────────────────────────────────────────────────────────────────────────────────────┐
│  ID      Artifact Digest       Type          Size          Vulnerabilities  Push Time     │
│ ───────────────────────────────────────────────────────────────────────────────────────── │
│                                                                                           │
└───────────────────────────────────────────────────────────────────────────────────────────┘
```

2025-02-05 02:20 UTC, bupd commented
merge conflicts!! && wait for #300 before merging

2025-03-15 23:01 UTC, bupd commented
merge conflicts!

2025-04-03 14:41 UTC, bupd commented
Yes, those Merge conflicts need to be fixed.

2025-04-04 05:53 UTC, bupd commented
sure go ahead

2025-04-09 02:44 UTC, rizul2108 commented
@bupd This PR can be closed as the same work has been done in PR #241 and the changes required in this PR are properly implemented and running in main branch

2025-04-09 05:31 UTC, closed without merging