User subcommand
goharbor/harbor-cli pull request #289
Opened 2024-12-20 02:27 UTC by Standing-Man

Add additional subcommand for user command
- `harbor user reset [username]` -> for reset the user's password
- `harbor user update [username]` -> for update the user's profile

2024-12-20 08:56 UTC, Standing-Man commented
Hi @Vad1mo, I’ve added two additional subcommands under `user` and wanted to check if it would be helpful to include a subcommand for setting a user’s role to Administrator or revoking the Administrator role.

2024-12-28 01:43 UTC, bupd commented
@Standing-Man Thanks for your contributions.

2024-12-28 02:03 UTC, bupd requested changes

2024-12-28 02:03 UTC, bupd commented on cmd/harbor/root/user/update.go
> +	flags.StringVarP(&opts.Realname, "realname", "r", "", "Realname of the user")
Add a flag to use userID directly
```suggestion
	flags.StringVarP(&opts.Realname, "realname", "r", "", "Realname of the user")
	flags.StringVarP(&UserID, "userID", "id", "", "ID of the user")
```

2024-12-28 02:03 UTC, bupd commented on pkg/api/user_handler.go
> +	log.Infof("User reset password successfully with id %d", userId)
```suggestion
	log.Infof("User password reset  successfully with id %d", userId)
```

2024-12-28 02:03 UTC, bupd commented on pkg/api/user_handler.go
> +	log.Info("user's profile updated successfully")
Maintain log messages consistently

2024-12-28 05:06 UTC, Standing-Man commented on cmd/harbor/root/user/reset.go
> +				userId, _ = api.GetUsersIdByName(args[0])
I modified the error handling of `api.GetUsersIdByName` because it doesn't raise an error even when the userId is not found.

2024-12-28 05:10 UTC, Standing-Man commented
enhance :
- add `--userID` flag on update subcommand  
- fix the error handler of `api.GetUsersIdByName`
- supplement the descriptions for reset and update
- maintain log messages consistently

2024-12-29 16:54 UTC, bupd commented on cmd/harbor/root/user/reset.go
> +				userId, _ = api.GetUsersIdByName(args[0])
Eventhough if we have problems with api. if you can fix then fixit. Otherwise It is Still its better to handle the error, Instead of ignoring it.

2024-12-29 16:55 UTC, bupd commented
@Standing-Man for the suggestions that are added mark the conversations as resolved. 
Thanks

2024-12-30 01:14 UTC, Standing-Man commented on cmd/harbor/root/user/reset.go
> +				userId, _ = api.GetUsersIdByName(args[0])
sure, i have solved this problem on new commit.

2024-12-30 01:17 UTC, Standing-Man commented
Thank you for your reminder @bupd. I have marked these conversations as resolved.

2025-01-14 07:09 UTC, Standing-Man commented
Hi @Vad1mo and @bupd, ready to review.

2025-02-05 02:07 UTC, bupd requested changes
Thanks for your contributions

I have left some suggestions for improvements.

2025-02-05 02:07 UTC, bupd commented on pkg/views/user/reset/view.go
> +					return nil
Add validation here for checking if old and new passwords match

![make sure old vs newe match pass](https://github.com/user-attachments/assets/23792fe1-210b-496b-b396-51c74c3b6f8f)

The above should result in and error.
Please add that check

2025-02-05 02:07 UTC, bupd commented on cmd/harbor/root/user/update.go
> +	flags.StringVarP(&opts.Realname, "realname", "r", "", "Realname of the user")
```suggestion
	flags := cmd.Flags()
	flags.Int64VarP(&UserID, "userID", "", 0, "ID of the user")
	flags.StringVarP(&opts.Comment, "comment", "", "", "Comment of the user")
	flags.StringVarP(&opts.Email, "email", "", "", "Email of the user")
	flags.StringVarP(&opts.Realname, "realname", "", "", "Realname of the user")
```

Please remove shortforms, as this might mislead users. 
also removing this will maintain consistency across the CLI.

2025-02-05 02:07 UTC, bupd commented on cmd/harbor/root/user/reset.go
> +
Also add flag here to enable reset the user's password via UserID directly.

2025-02-05 02:08 UTC, bupd commented on cmd/harbor/root/user/update.go
since harbor UI allows this

2025-02-05 08:43 UTC, Standing-Man commented on pkg/views/user/reset/view.go
> +					return nil
Hi @bupd, i have alredy added the checking if  the new password is same as the old's, but i'm confused about what this snapshot mean.

2025-02-05 10:56 UTC, Standing-Man commented
Hi @bupd, When I add a new command, I need to update the documentation. However, running `dagger call run-doc` and `go run doc.go` does not generate the corresponding command file.

2025-02-05 11:36 UTC, bupd commented on pkg/views/user/reset/view.go
> +					return nil
Password and confirm password should be the same.

2025-02-05 11:59 UTC, Standing-Man commented on pkg/views/user/reset/view.go
> +					return nil
<img width="608" alt="image" src="https://github.com/user-attachments/assets/9f736d71-983c-4cef-8913-dc3c8dcf3cc5" />
I had added a check to verify if the confirmation password matches the new password.

2025-02-10 12:41 UTC, bupd commented
The git history of this is not right. 

Can you fix these ones. @Standing-Man

2025-02-11 00:33 UTC, Standing-Man commented
> The git history of this is not right.
> 
> Can you fix these ones. @Standing-Man
Hi @bupd, I'm confused where the git history is wrong. Could you please point out?

2025-02-11 01:18 UTC, bupd requested changes
Please fix the git commit history. only update files that are necessary

![image](https://github.com/user-attachments/assets/0137f1a3-bb7f-43bf-80aa-64ac03e1e2ac)

![image](https://github.com/user-attachments/assets/fd54bf25-aa7b-4fd1-80bc-9af384e0d118)

2025-02-12 08:03 UTC, Standing-Man commented
Hi @bupd, I resolved the git history issue by submitting PR #330.

2025-02-26 02:42 UTC, closed without merging