Added the metadata command inside project command.
goharbor/harbor-cli pull request #92
Opened 2024-05-28 23:25 UTC by muaz-32

The metadata will be added directly using the command, without using the interactive cmd. As this is the fastest way to add metadata, so better user experience.
For example: `project metadata add [NAME|ID] ...[KEY]:[VALUE]`

2024-05-31 06:29 UTC, muaz-32 commented
> Thank you ! Please check out the latest changes we've made, they significantly improve how the handler is used

I have updated it accordingly. Also, I am updating my other PRs.

2024-05-31 06:30 UTC, muaz-32 commented
> > Thank you ! Please check out the latest changes we've made, they significantly improve how the handler is used
> 
> I have updated it accordingly. Also, I am updating my other PRs.

2024-05-31 06:34 UTC, muaz-32 commented
> Thank you ! Please check out the latest changes we've made, they significantly improve how the handler is used

Regarding the new changes, how should the flags be handled? For example this PR has the `isBool` flag, but most other commands do not have it. So the `isBool` flag is not included in the `ListFlags` struct. I think we can create individual structs for the commands. WDYT?

2025-04-29 13:19 UTC, Vad1mo commented
Metadata is essentially the project specific configuration, as it is marked like that on the UI we should follow the same convention, and name it Configuration.

Example:
```sh
harbor-cli project config add project_name key value
```

2025-05-06 12:36 UTC, bupd requested changes

2025-05-06 12:37 UTC, bupd commented
closing in favor of https://github.com/goharbor/harbor-cli/pull/448

2025-05-06 12:37 UTC, closed without merging